//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Pierogi.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PierogiParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IPierogiListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.packagePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackagePath([NotNull] PierogiParser.PackagePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.packagePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackagePath([NotNull] PierogiParser.PackagePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.packageSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageSpecifier([NotNull] PierogiParser.PackageSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.packageSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageSpecifier([NotNull] PierogiParser.PackageSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalarType([NotNull] PierogiParser.ScalarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalarType([NotNull] PierogiParser.ScalarTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] PierogiParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] PierogiParser.ArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.definedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinedType([NotNull] PierogiParser.DefinedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.definedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinedType([NotNull] PierogiParser.DefinedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] PierogiParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] PierogiParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.deprecatedAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeprecatedAnnotation([NotNull] PierogiParser.DeprecatedAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.deprecatedAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeprecatedAnnotation([NotNull] PierogiParser.DeprecatedAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] PierogiParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] PierogiParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.enumBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBranch([NotNull] PierogiParser.EnumBranchContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.enumBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBranch([NotNull] PierogiParser.EnumBranchContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDefinition([NotNull] PierogiParser.EnumDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDefinition([NotNull] PierogiParser.EnumDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructField([NotNull] PierogiParser.StructFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructField([NotNull] PierogiParser.StructFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDefinition([NotNull] PierogiParser.StructDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDefinition([NotNull] PierogiParser.StructDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.messageField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageField([NotNull] PierogiParser.MessageFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.messageField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageField([NotNull] PierogiParser.MessageFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.messageDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMessageDefinition([NotNull] PierogiParser.MessageDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.messageDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMessageDefinition([NotNull] PierogiParser.MessageDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] PierogiParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] PierogiParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSchema([NotNull] PierogiParser.SchemaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSchema([NotNull] PierogiParser.SchemaContext context);
}
