//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Pierogi.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PierogiParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IPierogiVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.packagePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackagePath([NotNull] PierogiParser.PackagePathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.packageSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackageSpecifier([NotNull] PierogiParser.PackageSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalarType([NotNull] PierogiParser.ScalarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] PierogiParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.definedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinedType([NotNull] PierogiParser.DefinedTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] PierogiParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.deprecatedAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeprecatedAnnotation([NotNull] PierogiParser.DeprecatedAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] PierogiParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.enumBranch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBranch([NotNull] PierogiParser.EnumBranchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.enumDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDefinition([NotNull] PierogiParser.EnumDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructField([NotNull] PierogiParser.StructFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.structDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDefinition([NotNull] PierogiParser.StructDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.messageField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageField([NotNull] PierogiParser.MessageFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.messageDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMessageDefinition([NotNull] PierogiParser.MessageDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefinition([NotNull] PierogiParser.DefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PierogiParser.schema"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema([NotNull] PierogiParser.SchemaContext context);
}
