//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Pierogi.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPierogiListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class PierogiBaseListener : IPierogiListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.packagePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackagePath([NotNull] PierogiParser.PackagePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.packagePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackagePath([NotNull] PierogiParser.PackagePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.packageSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPackageSpecifier([NotNull] PierogiParser.PackageSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.packageSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPackageSpecifier([NotNull] PierogiParser.PackageSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarType([NotNull] PierogiParser.ScalarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarType([NotNull] PierogiParser.ScalarTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] PierogiParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] PierogiParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.definedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinedType([NotNull] PierogiParser.DefinedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.definedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinedType([NotNull] PierogiParser.DefinedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] PierogiParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] PierogiParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.deprecatedAnnotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeprecatedAnnotation([NotNull] PierogiParser.DeprecatedAnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.deprecatedAnnotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeprecatedAnnotation([NotNull] PierogiParser.DeprecatedAnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] PierogiParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] PierogiParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.enumBranch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBranch([NotNull] PierogiParser.EnumBranchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.enumBranch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBranch([NotNull] PierogiParser.EnumBranchContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDefinition([NotNull] PierogiParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.enumDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDefinition([NotNull] PierogiParser.EnumDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.structField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructField([NotNull] PierogiParser.StructFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.structField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructField([NotNull] PierogiParser.StructFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDefinition([NotNull] PierogiParser.StructDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.structDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDefinition([NotNull] PierogiParser.StructDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.messageField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageField([NotNull] PierogiParser.MessageFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.messageField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageField([NotNull] PierogiParser.MessageFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.messageDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMessageDefinition([NotNull] PierogiParser.MessageDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.messageDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMessageDefinition([NotNull] PierogiParser.MessageDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] PierogiParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] PierogiParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PierogiParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchema([NotNull] PierogiParser.SchemaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PierogiParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchema([NotNull] PierogiParser.SchemaContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
